### ISSUE TITLE
TestApp does not build on VS2013

### ISSUE THREAD

**Issue by timmb** [ryanbartley/osc#1]
VS2013 doesn't seem to like having an #ifdef midway through a macro expansion. The macro at the end of testApp.cpp should be replaced with

    #if defined( CINDER_MSW )
    CINDER_APP(TestApp, RendererGl, [](App::Settings *settings) { settings->setConsoleWindowEnabled(); })
    #else
    CINDER_APP(TestApp, RendererGl);
    #endif

**Comment by timmb** [comment]
Proposed fix in PR https://github.com/ryanbartley/osc/pull/4

**Comment by ryanbartley** [comment]
The other samples need to be fixed in this way too. I'll fix them in a bit.

**Comment by ryanbartley** [comment]
Fully fixed by 1cedfb6f91fc3c896f5d4f057665f48b29cd6c19
