### ISSUE TITLE
Combination of arguments that fails under VS2013

### ISSUE THREAD

**Issue by timmb** [ryanbartley/osc#2]
Tested only in VS2013. This code fails to send/read correctly when added to testApp test:

    {
        mMessage2 = osc::Message("/message2");
        mMessage2.append(int32_t(i));
        mMessage2.append(int64_t(1));
        mMessage2.append(int64_t(-2));
        cout << "As constructed: " << mMessage2 << endl;
        mSender.send(mMessage2);
    }

//

    mReceiver.setListener("/message2",
      [&]( const osc::Message& message ) {
          cout << message << endl;
          auto messagesTheSame = (mMessage2 == message);
          cout << "Message2 the same: " << std::boolalpha << messagesTheSame << endl;
      });

Output:

    As constructed: Address: /message2
            <INTEGER_32>: 246
            <INTEGER_64>: 1
            <INTEGER_64>: -2

    Address: /message2
            <INTEGER_32>: 0
            <INTEGER_64>: 8589934591
            <INTEGER_64>: -8573288963

    Message2 the same: false

**Comment by ryanbartley** [comment]
None of the code has changed at all?

**Comment by timmb** [comment]
Yes this is without changing the append code

**Comment by ryanbartley** [comment]
I see it on my side to. I'm going to have to dig into this later as I'm at work right now.

**Comment by timmb** [comment]
You need the int32 in there for it to happen. Haven't got the code in front of me now to test but looks like it could be caused by the endian swap when the arguments are not aligned to 64bit boundaries?

**Comment by ryanbartley** [comment]
hmmm. Could be. I'll take a look when I get home.

**Comment by ryanbartley** [comment]
Looking into this a little deeper it seems like the types portion of the message isn't correctly being 32 bit aligned. Figuring out why that is.

**Comment by ryanbartley** [comment]
I fixed this with 57fe00864ab577f6bc90a2830a488938ea3c0449. Wasn't accounting for the ',' in the packet size.
