### ISSUE TITLE
Warning: 'ASIO_STANDALONE' macro redefined

### ISSUE THREAD

**Issue by gaborpapp** [ryanbartley/osc#7]
```
In file included from cinder/blocks/newosc/src/Osc.cpp:31:
In file included from cinder/blocks/newosc/src/Osc.h:39:
In file included from cinder/include/cinder/Buffer.h:25:
cinder/include/cinder/Cinder.h:42:9: warning: 'ASIO_STANDALONE' macro redefined
#define ASIO_STANDALONE 1
        ^
cinder/blocks/newosc/src/Osc.h:33:9: note: previous definition is here
#define ASIO_STANDALONE
        ^   
```

Maybe an include guard around the #define would help?

**Comment by ryanbartley** [comment]
There is one currently.

**Comment by gaborpapp** [comment]
Indeed, I haven't noticed this, sorry. The warning is coming from Cinder.h, where there is no guard.

**Comment by ryanbartley** [comment]
Ahh. I'm going to make a pr against cinder today. Maybe we can fix it then. I agree that the notice is annoying.

**Comment by ryanbartley** [comment]
I'm going to close this here because I've opened up a PR here https://github.com/cinder/Cinder/pull/1179. Will continue the conversation there.
